title: Sourcery
author: Freshprince95
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Part of an awesome Sourcing team and also working on an Events Strategy project. Areas from my sourcing work and research into the best Events strategy will be discussed here

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
